---
name: wordpress
director_uuid: CHANGE-ME

release:
  name: wordpress
  version: latest

compilation:
  workers: 8
  network: compile
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4

networks:

- name: compile
  subnets:
<% (0..63).each_with_index.map do |i| %>
  - range: 10.244.0.<%= i*4 %>/30
    reserved:
      - 10.244.0.<%= i*4 + 1 %>
    # static:
    #   - 10.244.0.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>
- name: default
  subnets:
<% (0..63).each_with_index.map do |i| %>
  - range: 10.244.1.<%= i*4 %>/30
    reserved:
      - 10.244.1.<%= i*4 + 1 %>
    static:
      - 10.244.1.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end
(0..63).each_with_index.map do |i| %>
  - range: 10.244.2.<%= i*4 %>/30
    reserved:
      - 10.244.2.<%= i*4 + 1 %>
    cloud_properties:
      name: random
<% end %>

resource_pools:

- name: infrastructure
  network: default
  size: 4
  stemcell:
    name: bosh-stemcell
    version: latest
  cloud_properties: {}


jobs:
  - name: mysql
    template: mysql
    instances: 1
    resource_pool: infrastructure
    networks:
    - name: default
      static_ips:
      - 10.244.1.2

  - name: wordpress
    template: wordpress
    instances: 1
    resource_pool: infrastructure
    networks:
    - name: default
      static_ips:
      - 10.244.1.6

  - name: nginx
    template: nginx
    instances: 2
    resource_pool: infrastructure
    networks:
    - name: default
      default: [dns, gateway]
      static_ips:
        - 10.244.1.10
        - 10.244.1.14

properties:
  wordpress:
    admin: foo@bar.com
    port: 8008
    servers:
      - 10.244.1.6
    servername: wp.appcloud14.dev.mozycloud.com
    db:
       name: wp
       user: wordpress
       pass: w0rdpr3ss
    auth_key: random key
    secure_auth_key: random key
    logged_in_key: random key
    nonce_key: random key
    auth_salt: random key
    secure_auth_salt: random key
    logged_in_salt: random key
    nonce_salt: random key

  mysql:
    address: 10.244.1.2
    port: 3306
    password: rootpass

  nginx:
    workers: 1
